version: '3.9'

networks:
  app-tier:
    driver: bridge

services:
  kafka-java-benchmark-app:
    image: nahwu2/kafka-java-benchmark:0.0.1
    restart: always
    networks:
      - app-tier
    ports:
      - "8003:8003"
    depends_on:
      - "kafka"

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    networks:
      - app-tier
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:3.3.1
    networks:
      - app-tier
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
